apiVersion: v1
kind: ServiceAccount
metadata:
  name: matchmaker-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: matchmaker-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: matchmaker-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: matchmaker-role
subjects:
  - kind: ServiceAccount
    name: matchmaker-sa
